Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -14,25 +14,25 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Set Default Scheme
+      - name: Set Default Scheme and Build
         run: |
-          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
-          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
-          
-          # Si el esquema es 'default', intenta leer un archivo llamado 'default'
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          
-          # Busca el archivo .xcworkspace o .xcodeproj en la carpeta iosApp
-          if [ "`ls -A iosApp | grep -i \\.xcworkspace\$`" ]; then 
-            filetype_parameter="workspace" 
-            file_to_build="`ls -A iosApp | grep -i \\.xcworkspace\$`"
-          else 
-            filetype_parameter="project" 
-            file_to_build="`ls -A iosApp | grep -i \\.xcodeproj\$`"
+          # Obtener el dispositivo iPhone para pruebas
+          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
+          if [ -z "$scheme" ] || [ "$scheme" = "default" ]; then
+            scheme="YourSchemeName"  # Reemplaza con el nombre de tu esquema
           fi
-
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "iosApp/$file_to_build" -destination "platform=$platform,name=$device"
+          if [ -n "`ls -A iosApp | grep -i \\.xcworkspace\$`" ]; then
+            filetype_parameter="workspace"
+            file_to_build=$(ls -A iosApp | grep -i \\.xcworkspace\$)
+          elif [ -n "`ls -A iosApp | grep -i \\.xcodeproj\$`" ]; then
+            filetype_parameter="project"
+            file_to_build=$(ls -A iosApp | grep -i \\.xcodeproj\$)
+          else
+            echo "Error: No se encontró un archivo .xcworkspace o .xcodeproj en iosApp."
+            exit 1
+          fi
+          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
+          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "iosApp/$file_to_build" -destination "platform=iOS Simulator,name=$device"
           
       - name: Build
         env:
